// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bind(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Run():Promise<void>;

export function ShowMessageDialog(arg1:string,arg2:string):Promise<void>;
